// This file was autogenerated by app/components/closurelibrary/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/App/App.js', ['App'], ['App.core.todo.Todo']);
goog.addDependency('../../../../js/App/core/todo/Todo.js', ['App.core.todo.Todo'], ['App.ui.Todo']);
goog.addDependency('../../../../js/App/ui/Component.js', ['App.ui.todo.Component'], ['App.ui.todo.AddForm', 'App.ui.todo.List']);
goog.addDependency('../../../../js/App/ui/Todo.js', ['App.ui.Todo'], ['App.ui.todo.AddForm', 'App.ui.todo.List']);
goog.addDependency('../../../../js/App/ui/atomic/Button.js', ['App.ui.atomic.Button'], []);
goog.addDependency('../../../../js/App/ui/atomic/Input.js', ['App.ui.atomic.Input'], []);
goog.addDependency('../../../../js/App/ui/todo/AddForm.js', ['App.ui.todo.AddForm'], ['App.ui.atomic.Button', 'App.ui.atomic.Input']);
goog.addDependency('../../../../js/App/ui/todo/Component.js', ['App.ui.todo.Component'], ['App.ui.todo.AddForm', 'App.ui.todo.List']);
goog.addDependency('../../../../js/App/ui/todo/List.js', ['App.ui.todo.List'], []);
goog.addDependency('../../../../js/App/ui/todo/Todo.js', ['App.ui.todo.Todo'], ['App.ui.todo.AddForm', 'App.ui.todo.List']);
