// This file was autogenerated by app/components/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/App/App.js', ['App', 'App.init'], ['App.components.TodoList', 'App.components.todoList.Todo', 'App.components.todoList.TodoCollection', 'goog.ui.IdGenerator'], false);
goog.addDependency('../../../../js/App/components/TodoList.js', ['App.components.TodoList'], ['App.ui.Todo'], false);
goog.addDependency('../../../../js/App/components/todoList/Todo.js', ['App.components.todoList.Todo'], [], false);
goog.addDependency('../../../../js/App/components/todoList/TodoCollection.js', ['App.components.todoList.TodoCollection'], ['App.components.todoList.Todo'], false);
goog.addDependency('../../../../js/App/ui/Todo.js', ['App.ui.Todo'], ['App.ui.todo.AddForm', 'App.ui.todo.List'], false);
goog.addDependency('../../../../js/App/ui/atomic/Button.js', ['App.ui.atomic.Button'], [], false);
goog.addDependency('../../../../js/App/ui/atomic/Input.js', ['App.ui.atomic.Input'], [], false);
goog.addDependency('../../../../js/App/ui/todo/AddForm.js', ['App.ui.todo.AddForm'], ['App.ui.atomic.Button', 'App.ui.atomic.Input'], false);
goog.addDependency('../../../../js/App/ui/todo/List.js', ['App.ui.todo.List'], ['App.ui.todo.ListItem'], false);
goog.addDependency('../../../../js/App/ui/todo/ListItem.js', ['App.ui.todo.ListItem'], [], false);
